1:print numpy version

In [1]:
import numpy as np
print(np.__version__)

1.14.0


2: create 1D array from 0 to 9

In [4]:
a1 = np.arange(10)
# arange([start,] stop[, step,], dtype=None)
# Return evenly spaced values within a given interval.
print(a1)

[0 1 2 3 4 5 6 7 8 9]


3:create a boolean array

In [6]:
b1 = np.full((3,3),True, dtype = bool)
b2 = np.ones((3,3), dtype=bool)
print(b1)
print(b2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4:extract odd number

In [7]:
a2 = a1[a1%2 == 1]
print(a2)

[1 3 5 7 9]


5: replace items

In [9]:
a1[a1%2 == 1] = -1
print(a1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6: replace items without affecting the original array

numpy.where(condition[, x, y])
Return elements, either from x or y, depending on condition

In [11]:
arr = np.arange(10)
out = np.where(arr%2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6: reshape

In [12]:
arr = np.arange(10)
print(arr.reshape(2,-1)) # setting to -1 automatically decides the number of cols


[[0 1 2 3 4]
 [5 6 7 8 9]]
